#!/bin/sh

# Case for systemd-coredump
if command -v coredumpctl >/dev/null; then
    echo "List of last coredump files"
    sudo coredumpctl list --no-pager -n 10
    echo
    read -p "Coredump file to debug (empty=last): " COREDUMP
    if [ -z "$COREDUMP" ]; then
        echo "Debug the last coredump file"
        sudo coredumpctl debug
    else
        echo "Debug the coredump file $COREDUMP"
        sudo coredumpctl debug "$COREDUMP"
    fi
else
    DIR="$(sysctl kernel.core_pattern | awk -F' ' '{print $3}' 2>&1)"
    DIR="${DIR%/*}"

    # Case of |/usr/share/apport/apport
    if echo "${DIR}" | grep -sq -e '|/.*apport'; then
        DIR=/var/crash
    fi

    echo "Coredump files folder: $DIR"
    echo "Last coredump files"

    if ! [ -d "$DIR" ]; then
        echo >&2 "Cannot find folder '$DIR'... abort !"
        exit 1
    fi

    ls -lt "$DIR" | tail -n +2 | head -n 8
    echo

    read -p "Coredump file to debug (empty=last): " COREDUMP
    if [ -z "$COREDUMP" ]; then
        echo "Debug the last coredump file"
        COREDUMP="$DIR/$(ls -tr "$DIR" | tail -n 1)"
    fi
    if [ -f "$DIR/$COREDUMP" ]; then
        COREDUMP="$DIR/$COREDUMP"
    fi

    BINARY="$(sudo gdb -c "$COREDUMP" --quiet -ex quit 2>&1 | awk -F'`' '/Core was generated by/{print $2}' | cut -d' ' -f1)"
    if [ -n "$BINARY" ] && [ -f "$BINARY" ]; then
        echo "Found binary $BINARY ..."
    else
        echo >&2 "Cannot identify the binary to use with coredump file $COREDUMP ... abort!"
        exit 1
    fi

    echo "Debug the coredump file $COREDUMP using binary $BINARY"
    echo

    sudo gdb -q -c "$COREDUMP" "$BINARY"
fi
