#!/bin/sh
# Git annex wrapper

# Forbid git annex initremote or enableremote when git config contains a reference to gcrypt
if [ -z "$GIT_ANNEX_ALLOW_GCRYPT" ] && git config -l 2>/dev/null | grep -i gcrypt >/dev/null; then
    for P; do
        if [ "$P" = "initremote" ] || [ "$P" = "enableremote" ]; then
            echo >&2 "Git annex $P is forbidden when gcrypt is used..."
            exit 1
        fi
    done
fi

# Execute git-annex
THIS="$([ -n "$BASH_VERSION" ] && echo "${BASH_SOURCE[0]}" || readlink -f "$0")"
PRGM="$(which -a git-annex 2>/dev/null | grep -v "$THIS" | head -n 1)"
exec "${PRGM:-/usr/bin/git-annex}" "$@"
